export enum ErrorCode {
  // AUTH
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED",
  AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED",
  AUTH_OAUTH_PROVIDER_ERROR = "AUTH_OAUTH_PROVIDER_ERROR",
  AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",

  // VALIDATION
  VALIDATION_FAILED = "VALIDATION_FAILED",
  VALIDATION_INVALID_PAYLOAD = "VALIDATION_INVALID_PAYLOAD",
  VALIDATION_MISSING_FIELD = "VALIDATION_MISSING_FIELD",
  VALIDATION_INVALID_TYPE = "VALIDATION_INVALID_TYPE",
  VALIDATION_FIELD_REQUIRED = "VALIDATION_FIELD_REQUIRED",
  VALIDATION_FIELD_INVALID_FORMAT = "VALIDATION_FIELD_INVALID_FORMAT",
  VALIDATION_FIELD_TOO_SHORT = "VALIDATION_FIELD_TOO_SHORT",
  VALIDATION_FIELD_TOO_LONG = "VALIDATION_FIELD_TOO_LONG",
  VALIDATION_FIELD_TOO_SMALL = "VALIDATION_FIELD_TOO_SMALL",
  VALIDATION_FIELD_TOO_LARGE = "VALIDATION_FIELD_TOO_LARGE",
  VALIDATION_FIELD_NOT_ALLOWED = "VALIDATION_FIELD_NOT_ALLOWED",
  VALIDATION_FIELD_NOT_UNIQUE = "VALIDATION_FIELD_NOT_UNIQUE",
  VALIDATION_FIELD_OUT_OF_RANGE = "VALIDATION_FIELD_OUT_OF_RANGE",
  VALIDATION_FIELD_ENUM_INVALID = "VALIDATION_FIELD_ENUM_INVALID",

  // DOMAIN
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",
  RESOURCE_CONFLICT = "RESOURCE_CONFLICT",
  RESOURCE_LOCKED = "RESOURCE_LOCKED",
  RESOURCE_DELETED = "RESOURCE_DELETED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_EMAIL_ALREADY_USED = "USER_EMAIL_ALREADY_USED",
  USER_USERNAME_ALREADY_USED = "USER_USERNAME_ALREADY_USED",
  USER_INVALID_STATE = "USER_INVALID_STATE",
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID",
  ORDER_OUT_OF_STOCK = "ORDER_OUT_OF_STOCK",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_DECLINED = "PAYMENT_DECLINED",
  PAYMENT_PROVIDER_ERROR = "PAYMENT_PROVIDER_ERROR",

  // CONFLICT
  CONFLICT_VERSION_MISMATCH = "CONFLICT_VERSION_MISMATCH",
  CONFLICT_DUPLICATE_ENTRY = "CONFLICT_DUPLICATE_ENTRY",
  CONFLICT_INVALID_STATE_TRANSITION = "CONFLICT_INVALID_STATE_TRANSITION",

  // RATE LIMIT
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",

  // SYSTEM
  SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR",
  SYSTEM_DEPENDENCY_FAILURE = "SYSTEM_DEPENDENCY_FAILURE",
  SYSTEM_TIMEOUT = "SYSTEM_TIMEOUT",
  SYSTEM_DATABASE_ERROR = "SYSTEM_DATABASE_ERROR",
  SYSTEM_CACHE_ERROR = "SYSTEM_CACHE_ERROR",
  SYSTEM_IO_ERROR = "SYSTEM_IO_ERROR",
  SYSTEM_CONFIGURATION_ERROR = "SYSTEM_CONFIGURATION_ERROR",

  // API
  API_NOT_FOUND = "API_NOT_FOUND",
  API_METHOD_NOT_ALLOWED = "API_METHOD_NOT_ALLOWED",
  API_UNSUPPORTED_MEDIA_TYPE = "API_UNSUPPORTED_MEDIA_TYPE",
  API_BAD_REQUEST = "API_BAD_REQUEST",
  API_VERSION_NOT_SUPPORTED = "API_VERSION_NOT_SUPPORTED",
}
